<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/6
 * Time: 9:52
 */
namespace app\admin\controller;

use think\Controller;

class Base extends Controller{


    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

}