<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/6
 * Time: 9:52
 */
namespace app\admin\controller;

use think\Controller;
use think\Session;

class Base extends Controller{


    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->checkAdmin();

    }


    protected function makeJson($code,$message,$data = null){
        return json(['code'=>$code,'message'=>$message,'data'=>$data]);
    }

    protected function checkAdmin()
    {
    	$admin = Session::get('admin');
    	if (!$admin) {
    		$this->redirect('/admin/login');
    	}
    }
}