<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/6
 * Time: 9:52
 */
namespace app\home\controller;

use think\Controller;
use think\Session;

class Base extends Controller{


    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->checkUser();
    }

    protected function makeJson($code,$message,$data = null){
        return json(['code'=>$code,'message'=>$message,'data'=>$data]);
    }

    protected function checkUser()
    {
    	$user = Session::get('user');
    	var_dump($user);
    	if (!$user) {
    		$this->redirect('/');
    	}
    }

}